import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema public,auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated; create publication supabase_realtime;`);
await db.exec(await readFile(new URL('../supabase/migrations/001_orders.sql',import.meta.url),'utf8'));
const staff='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
await db.exec(`insert into auth.users values ('${staff}'),('${other}'); insert into public.staff values ('${staff}','Nebi',true);`);
const payload={customer_name:'Test Müşteri',phone:'0532 111 22 33',delivery_date:'2026-10-01',delivery_time:'14:30',cake_type:'Çikolatalı',size:'8 kişilik',cake_message:'Mutlu yıllar',notes:'Test',price:1200,payment_status:'Kapora Alındı'};
async function rejects(sql:string,params:unknown[]=[]){await assert.rejects(()=>db.query(sql,params));}
await db.exec(`set role anon`);
await rejects('select * from public.orders');
await rejects('select public.save_order($1,$2)',[payload,crypto.randomUUID()]);
await db.exec(`reset role; set request.jwt.claim.sub='${other}'; set role authenticated`);
assert.equal((await db.query('select * from public.orders')).rows.length,0);
await rejects('select public.save_order($1,$2)',[payload,crypto.randomUUID()]);
await db.exec(`reset role; set request.jwt.claim.sub='${staff}'; set role authenticated`);
const requestId=crypto.randomUUID();
const saved=await db.query<any>('select * from public.save_order($1,$2)',[payload,requestId]);let order=saved.rows[0];
assert.equal(order.staff_name,'Nebi');assert.equal(order.created_by,staff);assert.equal(order.phone,'05321112233');assert.equal(order.status,'Yeni');
assert.equal((await db.query<any>('select * from public.save_order($1,$2)',[payload,requestId])).rows[0].id,order.id);
await rejects("update public.orders set status='Hazır'");
await rejects('select public.set_order_status($1,$2,$3)',[order.id,'Teslim Edildi',order.version]);
order=(await db.query<any>('select * from public.save_order($1,$2,$3,$4)',[{...payload,price:1400},crypto.randomUUID(),order.id,order.version])).rows[0];
assert.equal(Number(order.price),1400);
await rejects('select public.save_order($1,$2,$3,$4)',[payload,crypto.randomUUID(),order.id,1]);
for(const status of ['Hazırlanıyor','Hazır','Teslim Edildi']){order=(await db.query<any>('select * from public.set_order_status($1,$2,$3)',[order.id,status,order.version])).rows[0];assert.equal(order.status,status);}
assert.equal((await db.query('select * from public.order_status_history')).rows.length,4);
await rejects('select public.save_order($1,$2,$3,$4)',[payload,crypto.randomUUID(),order.id,order.version]);
await rejects('select public.set_order_status($1,$2,$3)',[order.id,'Yeni',order.version]);
await rejects('select public.save_order($1,$2)',[{...payload,price:-1},crypto.randomUUID()]);
await rejects('select public.save_order($1,$2)',[{...payload,phone:'123'},crypto.randomUUID()]);
const cancel=(await db.query<any>('select * from public.save_order($1,$2)',[payload,crypto.randomUUID()])).rows[0];
await db.query('select public.set_order_status($1,$2,$3)',[cancel.id,'İptal',cancel.version]);
await db.exec(`reset role; set role anon`);
assert.equal((await db.query('select * from public.track_order($1,$2)',[order.order_number,'wrong'])).rows.length,0);
const tracked=(await db.query<any>('select * from public.track_order($1,$2)',[order.order_number,order.tracking_code])).rows[0];
assert.equal(tracked.status,'Teslim Edildi');assert.equal(tracked.customer_name,undefined);assert.equal(tracked.phone,undefined);assert.equal(tracked.notes,undefined);
await db.exec(`reset role; update public.staff set active=false; set role authenticated`);
assert.equal((await db.query('select * from public.orders')).rows.length,0);
await rejects('select public.save_order($1,$2)',[payload,crypto.randomUUID()]);
await db.close();console.log('PASS: creation, edit, idempotency, attribution, all transitions, cancellation, history, concurrent edit protection, validation, anonymous access, nonstaff access, deactivation, private tracking.');
