import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {validateImageFile,IMAGE_LIMIT} from '../lib/image-validation.ts';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema public,auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated; create publication supabase_realtime;
create schema storage;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text references storage.buckets(id),name text not null,unique(bucket_id,name));
alter table storage.objects enable row level security;
grant usage on schema storage to anon,authenticated;
grant select,insert,update,delete on storage.objects to anon,authenticated;`);
for(const file of ['001_orders.sql','002_order_images.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));
const bucket=(await db.query<any>('select * from storage.buckets')).rows[0];
assert.equal(bucket.public,false);assert.equal(Number(bucket.file_size_limit),IMAGE_LIMIT);assert.deepEqual(bucket.allowed_mime_types,['image/jpeg','image/png','image/webp']);
const staff='00000000-0000-4000-8000-000000000001',outsider='00000000-0000-4000-8000-000000000002';
await db.exec(`insert into auth.users values ('${staff}'),('${outsider}'); insert into public.staff values ('${staff}','Nebi',true);set request.jwt.claim.sub='${staff}';set role authenticated;`);
const payload={customer_name:'Test',phone:'05321112233',delivery_date:'2026-10-01',delivery_time:'14:30',cake_type:'Çilekli',size:'6 kişilik',price:900,payment_status:'Ödendi'};
const order=(await db.query<any>('select * from public.save_order($1,$2)',[payload,crypto.randomUUID()])).rows[0];
const put=(path:string)=>db.query("insert into storage.objects(bucket_id,name) values ('order-images',$1) returning name",[path]);
for(const slot of [1,2])assert.equal((await put(`${order.id}/${slot}`)).rows.length,1);
await assert.rejects(()=>put(`${order.id}/3`));
await assert.rejects(()=>put(`${order.id}/1.png`));
await assert.rejects(()=>put(`${order.id}/1`)); // no overwrite or race producing a third object
await assert.rejects(()=>put(`${crypto.randomUUID()}/1`));
assert.equal((await db.query('select * from storage.objects')).rows.length,2);
assert.equal((await db.query("update storage.objects set name='changed' returning *")).rows.length,0);
await db.exec(`reset role;set request.jwt.claim.sub='${outsider}';set role authenticated;`);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
assert.equal((await db.query('delete from storage.objects returning *')).rows.length,0);
await assert.rejects(()=>put(`${order.id}/1`));
await db.exec(`reset role;set role anon;`);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await assert.rejects(()=>put(`${order.id}/1`));
await db.exec(`reset role;set request.jwt.claim.sub='${staff}';set role authenticated;`);
assert.equal((await db.query('delete from storage.objects where name=$1 returning *',[`${order.id}/2`])).rows.length,1);
await put(`${order.id}/2`);
await db.query('select public.set_order_status($1,$2,$3)',[order.id,'İptal',order.version]);
assert.equal((await db.query('delete from storage.objects returning *')).rows.length,0);
assert.equal((await db.query('select * from storage.objects')).rows.length,2);
await assert.rejects(()=>put(`${order.id}/1`));
await db.exec('reset role;update public.staff set active=false;set role authenticated;');
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await db.close();
await validateImageFile(new File([new Uint8Array([137,80,78,71,13,10,26,10])],'test.png',{type:'image/png'}));
await assert.rejects(()=>validateImageFile(new File(['<svg/>'],'test.svg',{type:'image/svg+xml'})));
await assert.rejects(()=>validateImageFile(new File(['not a png'],'fake.png',{type:'image/png'})));
await assert.rejects(()=>validateImageFile(new File([new Uint8Array(IMAGE_LIMIT+1)],'big.png',{type:'image/png'})));
await assert.rejects(()=>validateImageFile(new File([],'empty.png',{type:'image/png'})));
console.log('PASS: two slots, third slot/alternate names/duplicates rejected, private access, removal/reupload, terminal order and inactive staff restrictions, bucket limits, image type/header/size checks.');
