import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon;create publication supabase_realtime;`);
await db.exec(await readFile(new URL('../supabase/migrations/001_orders.sql',import.meta.url),'utf8'));
const admin='00000000-0000-4000-8000-000000000001',member='00000000-0000-4000-8000-000000000002',second='00000000-0000-4000-8000-000000000003';
await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'admin@test.invalid',now())",[admin]);
await db.query("insert into public.staff(id,display_name,active) values($1,'Nebi',true)",[admin]);
const sql=await readFile(new URL('../supabase/migrations/005_memberships.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
await db.query('update public.staff set is_admin=true where id=$1',[admin]);
await db.query("insert into auth.users values($1,'member@test.invalid',null,$2)",[member,{display_name:'Personel',is_admin:true,active:true}]);
await db.query("insert into auth.users values($1,'second@test.invalid',now(),$2)",[second,{display_name:'Other'}]);
async function asUser(id:string){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
const payload={customer_name:'Test',phone:'05321112233',delivery_date:'2026-10-01',delivery_time:'12:00',cake_type:'Pasta',size:'8',price:100,payment_status:'Ödendi'};
await asUser(member);
let own=(await db.query<any>('select * from public.staff')).rows;assert.equal(own.length,1);assert.equal(own[0].is_admin,false);assert.equal(own[0].active,false);
await assert.rejects(()=>db.query('select public.admin_members()'));
await assert.rejects(()=>db.query("select public.admin_membership($1,'approve')",[member]));
await assert.rejects(()=>db.query('update public.staff set active=true,is_admin=true'));
await assert.rejects(()=>db.query('select public.save_order($1,$2)',[payload,crypto.randomUUID()]));
assert.equal((await db.query('select * from public.orders')).rows.length,0);
await asUser(admin);assert.equal((await db.query('select * from public.admin_members()')).rows.length,3);
await assert.rejects(()=>db.query("select public.admin_membership($1,'approve')",[member]));
await db.exec('reset role');await db.query('update auth.users set email_confirmed_at=now() where id=$1',[member]);
await asUser(admin);await db.query("select public.admin_membership($1,'approve')",[member]);
await assert.rejects(()=>db.query("select public.admin_membership($1,'delete')",[admin]));
await asUser(member);const order=(await db.query<any>('select * from public.save_order($1,$2)',[payload,crypto.randomUUID()])).rows[0];
await asUser(admin);await db.query("select public.admin_membership($1,'disable')",[member]);
await asUser(member);assert.equal((await db.query('select * from public.orders')).rows.length,0);await assert.rejects(()=>db.query('select public.set_order_status($1,$2,$3)',[order.id,'Hazırlanıyor',1]));
await asUser(admin);await db.query("select public.admin_membership($1,'approve')",[member]);await db.query("select public.admin_membership($1,'delete')",[member]);
assert.equal((await db.query('select * from public.admin_members()')).rows.length,2);
assert.equal((await db.query('select * from public.orders')).rows.length,1);
await assert.rejects(()=>db.query("select public.admin_membership($1,'approve')",[member]));
await asUser(member);assert.equal((await db.query('select * from public.orders')).rows.length,0);await assert.rejects(()=>db.query('select public.save_order($1,$2)',[payload,crypto.randomUUID()]));
await db.exec('reset role');await db.exec(sql);assert.equal((await db.query<any>('select active,deleted_at from public.staff where id=$1',[member])).rows[0].active,false);
await db.exec('set role anon');await assert.rejects(()=>db.query('select public.admin_members()'));
await db.close();console.log('PASS: signup cannot self-authorize, confirmation required, admin-only membership changes, self-protection, revocation with existing session, order history survives deletion, repeat-safe migration.');
