import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {archiveHtml} from '../lib/order-export.ts';
import {samples} from '../lib/orders.ts';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon;create publication supabase_realtime;create schema storage;create table storage.objects(bucket_id text,name text);`);
await db.exec(await readFile(new URL('../supabase/migrations/001_orders.sql',import.meta.url),'utf8'));
const staff='00000000-0000-4000-8000-000000000001';
await db.exec(`insert into auth.users values('${staff}');insert into public.staff values('${staff}','Nebi',true);set request.jwt.claim.sub='${staff}';`);
const data={customer_name:'Test',phone:'05321112233',delivery_date:'2020-01-01',delivery_time:'12:00',cake_type:'Pasta',size:'8',price:100,payment_status:'Ödendi'};
async function create(status:string){let o=(await db.query<any>('select * from public.save_order($1,$2)',[data,crypto.randomUUID()])).rows[0];for(const s of status==='İptal'?['İptal']:status==='Teslim Edildi'?['Hazırlanıyor','Hazır','Teslim Edildi']:[]){o=(await db.query<any>('select * from public.set_order_status($1,$2,$3)',[o.id,s,o.version])).rows[0];}return o;}
const old=await create('Teslim Edildi');
await db.query("update public.order_status_history set changed_at=now()-interval '8 days' where order_id=$1 and status='Teslim Edildi'",[old.id]);
await db.exec(await readFile(new URL('../supabase/migrations/003_retention.sql',import.meta.url),'utf8'));
const fresh=await create('Teslim Edildi'),cancelled=await create('İptal'),open=await create('Yeni');
assert.ok(fresh.delivered_at);
assert.deepEqual((await db.query<any>('select * from public.retention_candidates()')).rows.map(o=>o.id),[old.id]);
await db.exec('set role authenticated');
await assert.rejects(()=>db.query('select * from public.retention_candidates()'));
await assert.rejects(()=>db.query('select public.finish_order_retention($1)',[old.id]));
await db.exec('reset role;set role anon');
await assert.rejects(()=>db.query('select * from public.retention_candidates()'));
await db.exec('reset role');
for(const o of [fresh,cancelled,open])assert.equal((await db.query<any>('select public.finish_order_retention($1) as removed',[o.id])).rows[0].removed,false);
await db.query("insert into storage.objects values('order-images',$1)",[old.id+'/1']);
await assert.rejects(()=>db.query('select public.finish_order_retention($1)',[old.id]));
assert.equal((await db.query('select * from public.orders where id=$1',[old.id])).rows.length,1);
await db.exec('delete from storage.objects;set role service_role');
assert.equal((await db.query<any>('select public.finish_order_retention($1) as removed',[old.id])).rows[0].removed,true);
assert.equal((await db.query<any>('select public.finish_order_retention($1) as removed',[old.id])).rows[0].removed,false);
await db.exec('reset role');
assert.equal((await db.query('select * from public.order_status_history where order_id=$1',[old.id])).rows.length,0);
// A planned delivery date in the past must never trigger cleanup of open/cancelled orders.
assert.equal((await db.query('select * from public.orders')).rows.length,3);
// Boundary: 167h59m stays, exactly 168h is eligible.
await db.exec('begin;alter table public.orders disable trigger order_delivery_stamp');
await db.query("update public.orders set delivered_at=now()-interval '167 hours 59 minutes' where id=$1",[fresh.id]);
assert.equal((await db.query('select * from public.retention_candidates()')).rows.length,0);
await db.query("update public.orders set delivered_at=now()-interval '168 hours' where id=$1",[fresh.id]);
assert.equal((await db.query('select * from public.retention_candidates()')).rows.length,1);
await db.exec('rollback');
const sample={...samples()[0],notes:'</script><script>alert(1)</script>',customer_name:'<img src=x onerror=alert(1)>'};
const html=archiveHtml([{order:sample,history:[],images:[]}],new Date().toISOString());
assert.ok(!html.includes('<script>alert(1)'));
assert.ok(html.includes('&lt;img'));
const json=html.match(/id="siparis-pastam-backup">([\s\S]*?)<\/script>/)![1];
assert.deepEqual(JSON.parse(json).entries[0].order,sample);
assert.throws(()=>archiveHtml([{order:sample,history:[],images:[{name:'1',data_url:'javascript:alert(1)'}]}],new Date().toISOString()));
await db.close();
console.log('Retention: delivery timestamp, 168h boundary, open/cancelled protection, authorization, storage guard, history cleanup, retry and safe archive passed.');
