import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon;create publication supabase_realtime;`);
await db.exec(await readFile(new URL('../supabase/migrations/001_orders.sql',import.meta.url),'utf8'));
const staff='00000000-0000-4000-8000-000000000001';
await db.exec(`insert into auth.users values('${staff}');insert into public.staff values('${staff}','Nebi',true);set request.jwt.claim.sub='${staff}';`);
const payload={customer_name:'Test',phone:'05321112233',delivery_date:'2026-10-01',delivery_time:'12:00',cake_type:'Pasta',size:'8',price:100,payment_status:'Ödendi'};
const create=async()=> (await db.query<any>('select * from public.save_order($1,$2)',[payload,crypto.randomUUID()])).rows[0];
const old=await create();assert.equal(old.tracking_code.length,32);
const migration=await readFile(new URL('../supabase/migrations/004_short_tracking.sql',import.meta.url),'utf8');
await db.exec(migration);
const converted=(await db.query<any>('select * from public.orders where id=$1',[old.id])).rows[0];
assert.match(converted.tracking_code,/^[0-9A-F]{8}$/);assert.equal(converted.legacy_tracking_code,old.tracking_code);
await db.exec(migration);assert.equal((await db.query<any>('select tracking_code from public.orders where id=$1',[old.id])).rows[0].tracking_code,converted.tracking_code);
const fresh=await create();assert.match(fresh.tracking_code,/^[0-9A-F]{8}$/);assert.equal(fresh.legacy_tracking_code,null);
await db.exec('set role anon');
const track=async(number:string,code:string)=>(await db.query<any>('select * from public.track_order($1,$2)',[number,code])).rows;
assert.equal((await track(old.order_number,old.tracking_code)).length,1);
assert.equal((await track(old.order_number,converted.tracking_code.toLowerCase())).length,1);
const result=await track(fresh.order_number,fresh.tracking_code);
assert.deepEqual(Object.keys(result[0]).sort(),['delivery_date','delivery_time','order_number','status','updated_at']);
await assert.rejects(()=>db.query('select * from public.tracking_attempts'));
await assert.rejects(()=>db.query('select public.new_tracking_code()'));
for(let i=0;i<10;i++)assert.equal((await track(fresh.order_number,'WRONG123')).length,0);
assert.equal((await track(fresh.order_number,fresh.tracking_code)).length,0);
assert.equal((await track(old.order_number,old.tracking_code)).length,1);
await db.exec('reset role');
await db.query("update public.tracking_attempts set started_at=now()-interval '16 minutes' where order_id=$1",[fresh.id]);
await db.exec('set role anon');assert.equal((await track(fresh.order_number,fresh.tracking_code)).length,1);
await db.exec('reset role');
const count=(await db.query<any>('select count(*)::int n from public.tracking_attempts')).rows[0].n;
await track('NB-NOT-FOUND','WRONG123');assert.equal((await db.query<any>('select count(*)::int n from public.tracking_attempts')).rows[0].n,count);
await db.query('delete from public.order_status_history where order_id=$1',[fresh.id]);await db.query('delete from public.orders where id=$1',[fresh.id]);assert.equal((await db.query('select * from public.tracking_attempts where order_id=$1',[fresh.id])).rows.length,0);
await db.close();console.log('PASS: short codes, old-code compatibility, repeat-safe migration, case handling, anonymous data minimization, server attempt limits/reset and retention cascade.');
