'use client';
import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
type Member={id:string;display_name:string;email:string;active:boolean;is_admin:boolean;email_confirmed:boolean};
export default function Members(){
 const [members,setMembers]=useState<Member[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);try{const {data,error}=await supabase.rpc('admin_members');if(error)throw error;setMembers(data??[]);}catch{setMembers([]);setError('Üyelikler yüklenemedi. Yönetici yetkinizi ve bağlantınızı kontrol edin.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 async function change(m:Member,action:string){if(!supabase||busy)return;if(action==='delete'&&!confirm(`${m.display_name} üyeliği silinsin mi? Uygulama erişimi kapanır. Eski sipariş kayıtları korunur. Bu ekrandan geri alınamaz.`))return;setBusy(true);setError('');setMessage('');try{const {error}=await supabase.rpc('admin_membership',{p_id:m.id,p_action:action});if(error)throw error;setMessage(action==='delete'?'Üyelik silindi.':action==='approve'?'Personel erişimi açıldı.':'Personel erişimi kapatıldı.');await load();}catch(e){setError((e as {message?:string}).message||'İşlem tamamlanamadı.');}finally{setBusy(false);}}
 return <><div className="pagehead"><div><h1>Üyelik yönetimi</h1><p className="muted">Yeni personeli onaylayın, erişimini durdurun veya üyeliğini silin.</p></div><button className="secondary" disabled={busy||loading} onClick={()=>{setError('');void load();}}>Yenile</button></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}<p className="small">Üyelik silindiğinde uygulama erişimi kapatılır. Aynı hesapla yeniden başvuru yapılabilir; tekrar yönetici onayı gerekir. Geçmiş siparişlerin personel bilgisi korunur; e-posta giriş hesabı Supabase’de kalır.</p><section className="panel"><div className="ordergrid">{members.map(m=><article className="ordercard" key={m.id}><h3>{m.display_name}</h3><p style={{overflowWrap:'anywhere'}}>{m.email}</p><p>{m.is_admin?'Yönetici':m.active?'Aktif personel':'Onay bekliyor / erişimi kapalı'}</p>{!m.is_admin&&<div className="actions"><button className="secondary" disabled={busy} onClick={()=>void change(m,m.active?'disable':'approve')}>{m.active?'Erişimi durdur':'Onayla / etkinleştir'}</button><button className="textbtn" disabled={busy} onClick={()=>void change(m,'delete')}>Üyeliği sil</button></div>}</article>)}</div>{loading&&<p>Üyelikler yükleniyor…</p>}{!loading&&!members.length&&!error&&<p>Üyelik bulunamadı.</p>}</section></>;
}
