import type {Order} from './orders';
export type SavedImage={name:string;data_url:string};
export type OrderArchive={order:Order;history:Record<string,unknown>[];images:SavedImage[]};
export function escapeHtml(value:unknown){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function archiveHtml(entries:OrderArchive[],exportedAt:string,demo=false){
 const e=escapeHtml;
 const forms=entries.map(({order:o,history,images})=>{
  const fields=[['Müşteri',o.customer_name],['Telefon',o.phone],['Planlanan teslim',`${o.delivery_date} ${o.delivery_time.slice(0,5)}`],['Pasta türü',o.cake_type],['Boyut',o.size],['Pasta üzeri yazı',o.cake_message||'—'],['Özel not',o.notes||'—'],['Fiyat',new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(o.price)],['Ödeme',o.payment_status],['Durum',o.status],['Siparişi alan',o.staff_name],['Gerçek teslim zamanı',o.delivered_at?new Date(o.delivered_at).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'}):'—'],['Müşteri takip kodu',o.tracking_code]];
  return `<article><h2>${e(o.order_number)}</h2><dl>${fields.map(([k,v])=>`<div><dt>${e(k)}</dt><dd>${e(v)}</dd></div>`).join('')}</dl><div class="images">${images.map(img=>{
   if(!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(img.data_url))throw new Error('Geçersiz yedek görseli.');
   return `<img alt="Pasta referans görseli" src="${img.data_url}">`;
  }).join('')}</div>${history.length?`<h3>Durum geçmişi</h3><ul>${history.map(h=>`<li>${e(h.status)} · ${e(new Date(String(h.changed_at)).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'}))}</li>`).join('')}</ul>`:''}</article>`;
 }).join('');
 const payload=JSON.stringify({format:'siparis-pastam-backup',version:1,exported_at:exportedAt,demo,entries}).replace(/</g,'\\u003c');
 return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sipariş Pastam · Sipariş formları</title><style>body{font:15px system-ui,sans-serif;color:#241b20;max-width:900px;margin:32px auto;padding:0 20px}h1,h2{color:#792f49}article{border:1px solid #ddd;border-radius:12px;margin:24px 0;padding:24px;break-after:page}dl{display:grid;grid-template-columns:1fr 1fr;gap:16px}dl div{break-inside:avoid}dt{font-size:12px;color:#666}dd{margin:4px 0;white-space:pre-wrap;overflow-wrap:anywhere}.images{display:flex;flex-wrap:wrap;gap:12px}.images img{max-width:45%;max-height:300px;object-fit:contain}button{background:#792f49;color:white;border:0;padding:12px 18px;border-radius:8px;cursor:pointer}li{margin:6px 0}@media(max-width:520px){dl{grid-template-columns:1fr}}@media print{.controls{display:none}body{margin:0;padding:0;font-size:11pt}article{border:0;padding:0;margin:0 0 20px}article:last-child{break-after:auto}h2,h3{break-after:avoid}.images{break-inside:avoid}dl{grid-template-columns:1fr 1fr}}@page{size:A4;margin:15mm}</style></head><body><header><h1>Sipariş Pastam</h1><p>${demo?'ÖRNEK VERİ · ':''}${entries.length} sipariş · Kaydetme: ${e(new Date(exportedAt).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'}))}</p><div class="controls"><button onclick="window.print()">Yazdır / PDF olarak kaydet</button><p>PDF için yazdırma penceresinde “PDF olarak kaydet” seçeneğini seçin. Bu dosya müşteri bilgileri ve özel takip kodları içerir; güvenli bir yerde saklayın.</p></div></header>${forms}<script type="application/json" id="siparis-pastam-backup">${payload}</script></body></html>`;
}
